### ISSUE TITLE
Create a minimal web user interface

### ISSUE THREAD

**Issue by Steffo99** [Steffo99/mandarin#10]
Tra i requisiti c'è che il progetto deve avere un'interfaccia grafica per gli utenti, non è sufficiente un'interfaccia command line.

Visto che però il progetto si basa su una web API, creare una cosa bellina dovrebbe essere rapido e indolore!

**Comment by meschio94** [comment]
Cosa consigli di guardare per partire nel caso volessi provare io a buttare giù una mezza GUI ?

**Comment by Steffo99** [comment]
beh, l'idea più facile sarebbe fare qualcosina in HTML, CSS e Javascript...

se non l'hai usato molto si potrebbe usare qualcosa come [Bootstrap](https://getbootstrap.com/docs/5.0/getting-started/introduction/) che contiene già tanti componenti già pronti
