### ISSUE TITLE
Define the default thesaurus

### ISSUE THREAD

**Issue by Steffo99** [Steffo99/mandarin#6]
Mandarin permette già di creare il proprio thesaurus, in quanto persone diverse potrebbero non concordare su un'unica gerarchia di generi.

Se dobbiamo fare una demo, dobbiamo però creare noi un thesaurus da usarci!

**Comment by meschio94** [comment]
Il problema del thesaurus non si potrebbe risolvere su multi categorie di un brano ?

Ad esempio canzone X può essere sia Rock, che Dubstep, o il quesito si basa sul fatto che qualcuno potrebbe definrie dubstep un genere diverso, chessò il classico ?

**Comment by Steffo99** [comment]
sì, è già così ^^

bisogna solo scrivere una gerarchia di generi, un po' come su [questa pagina di wikipedia](https://en.wikipedia.org/wiki/List_of_popular_music_genres)

**Comment by Steffo99** [comment]
https://musicmap.info/

**Comment by Steffo99** [comment]
Finito il tool per aggiungere automaticamente i generi al database, adesso bisogna completare il file [`default_thesaurus.json`](https://github.com/Steffo99/mandarin/blob/ts/default_thesaurus.json)
